[settings]
experimental = true
disable_backends = ["asdf", "vfox"]
idiomatic_version_file_enable_tools = ["python"]

[settings.pipx]
uvx = true

[settings.npm]
package_manager = "pnpm"

[tools]
node = "lts"

terraform = "latest"

"aqua:astral-sh/uv" = "latest"
"aqua:pnpm/pnpm" = "latest"
"aqua:pre-commit/pre-commit" = "latest"

