[settings]
experimental = true
disable_backends = ["asdf", "vfox"]
idiomatic_version_file_enable_tools = ["python"]

[settings.pipx]
uvx = true

[settings.npm]
package_manager = "pnpm"

[tools]
# JS/TS
node = "lts"
pnpm = "latest"

# Python
uv = "latest"
ty = "latest"

# Other
terraform = "latest"
pre-commit = "latest"

# npm packages
"npm:@aikidosec/safe-chain" = "latest"
"npm:agent-browser" = "latest"
"npm:@playwright/cli" = "latest"
"npm:@typescript/native-preview" = "latest"

"pipx:claude-code-log" = "latest"
