[settings]
experimental = true
disable_backends = ["asdf", "vfox"]
idiomatic_version_file_enable_tools = ["python"]

[settings.pipx]
uvx = true

[tools]
1password = "latest"
claude = "latest"
duckdb = "latest"
gemini = "latest"
node = "22"
pre-commit = "latest"
terraform = "latest"
uv = "latest"
