add_newline = true

# ----------------------------------------------------
# format
# ----------------------------------------------------
format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$aws\
$gcloud\
$fill\
$cmd_duration\
$time\
\n$character\
"""

# ----------------------------------------------------
# left module
# ----------------------------------------------------
[directory]
truncation_length = 6
truncation_symbol = ' '
truncate_to_repo = false
home_symbol = '~'
read_only = ' 󰌾 '
format = """
[](fg:#333844)\
[$path]($style)\
[$read_only]($read_only_style)\
[](fg:#333844)\
"""
style = 'bold fg:#769ff0 bg:#333844'
read_only_style = 'bold fg:#313244 bg:#333844'

[git_branch]
symbol = ""
style = "fg:#ffffff bg:#232925"
format = """
[](fg:#232925)\
[$symbol $branch]($style)\
"""

[git_status]
style = "fg:#ffffff bg:#232925"
format = """
[$all_status$ahead_behind]($style)\
[](fg:#232925)\
"""

[python]
python_binary = [["uv", "run", "--no-python-downloads", "--no-project", "python"]]
format = """
[](fg:#ffcb6b)\
[ $version]($style)\
[](fg:#ffcb6b)\
"""
style = "bold fg:#313244 bg:#ffcb6b"

[nodejs]
# 色は公式のビジュアルガイドラインより
format = """
[](fg:#66cc33)\
[ $version]($style)\
[](fg:#66cc33)\
"""
style = "bold fg:#313244 bg:#66cc33"

[gcloud]
format = '[ $symbol $project(\($domain\))]($style) '
symbol = " "
style = 'bold blue'

[aws]
format = '[ $symbol $profile]($style)'
symbol = " "
style = "bold fg:#ff9900"

[fill]
symbol = ' '

# ----------------------------------------------------
# right module
# ----------------------------------------------------
[cmd_duration]
min_time = 1
style = 'fg:#e0af68'
format = "[ $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[[  $time](fg:#a0a9cb)]($style)'
