add_newline = true


# ----------------------------------------------------
# left module
# ----------------------------------------------------
[directory]
truncation_length = 6
truncation_symbol = 'ÔÅº '
truncate_to_repo = false
home_symbol = '~'
read_only = ' Û∞åæ '
format = """
[ÓÇ∂](fg:#80EBDF)\
[$path]($style)\
[$read_only]($read_only_style)\
[ÓÇº](fg:#80EBDF)\
"""
style = 'bold fg:#313244 bg:#80EBDF'
read_only_style = 'bold fg:#313244 bg:#80EBDF'

[git_branch]
symbol = "Ôêò"
style = "fg:#769ff0 bg:#333844"
format = """
[ÓÇ∫](fg:#333844)\
[$symbol $branch]($style)\
"""

[git_status]
style = "fg:#769ff0 bg:#333844"
format = """
[$all_status$ahead_behind]($style)\
[ÓÇº](fg:#333844)\
"""

# ----------------------------------------------------
# Google Cloud module
# ----------------------------------------------------
[gcloud]
format = '[gcloud on $symbol$project(\($domain\))]($style) '
style = 'bold blue'

# ----------------------------------------------------
# AWS module
# ----------------------------------------------------
[aws]
format = '[$symbol $profile ]($style)'
symbol = "üí≠"
style = "bold fg:#ff9900"
